insert into t_bible_verse (text, address) values ("Lecz ci, co zaufali Panu, odzyskują siły, otrzymują skrzydła jak orły: biegną bez zmęczenia, bez znużenia idą", "Iz 40,31");
insert into t_bible_verse (text, address) values ("Nie sądźcie, abyście nie byli sądzeni. Bo takim sądem, jakim sądzicie, i was osądzą; i taką miarą jaką wy mierzycie, wam odmierzą", "Mt 7,1");
insert into t_bible_verse (text, address) values ("Bóg jest światłością, a nie ma w Nim żadnej ciemności.", "1 J 1,5b");
insert into t_bible_verse (text, address) values ("Niech przeto ten, komu się zdaje, że stoi, baczy, aby nie upadł.", "1 Kor 10,12");
insert into t_bible_verse (text, address) values ("Bądźcie trzeźwi! Czuwajcie! Przeciwnik wasz, diabeł, jak lew ryczący krąży szukając kogo pożreć.", "1 P 5,8");
insert into t_bible_verse (text, address) values ("Kamień odrzucony przez budujących stał się kamieniem węgielnym. Stało się to przez Pana: cudem jest w oczach naszych. Oto dzień, który Pan uczynił: radujmy się zeń i weselmy!", "Ps 118,22-24");
insert into t_bible_verse (text, address) values ("Miłosierny jest Pan i łaskawy, nieskory do gniewu i bardzo łagodny. Nie wiedzie sporu do końca i nie płonie gniewem na wieki. Nie postępuje z nami według naszych grzechów ani według win naszych nam nie odpłaca.", "Ps 103,8-10");
insert into t_bible_verse (text, address) values ("Bo kto chce zachować swoje życie, straci je; a kto straci swe życie z mego powodu, znajdzie je.", "Mt 16,25");
insert into t_bible_verse (text, address) values ("Cóż bowiem za korzyść odniesie człowiek, choćby cały świat zyskał, a na swej duszy szkodę poniósł?", "Mt 16,26");
insert into t_bible_verse (text, address) values ("Oto przyjdę niebawem, a moja zapłata jest ze Mną, by tak każdemu odpłacić, jaka jest jego praca. Jam Alfa i Omega, Pierwszy i Ostatni, Początek i Koniec.", "Ap 22,12");
insert into t_bible_verse (text, address) values ("I wszystko, cokolwiek działacie słowem lub czynem, wszystko (czyńcie) w imię Pana Jezusa, dziękując Bogu Ojcu przez Niego.",  "Kol 3,18");
insert into t_bible_verse (text, address) values ("Gniewajcie się, a nie grzeszcie: niech nad waszym gniewem nie zachodzi słońce!",  "Ef 4,26");
insert into t_bible_verse (text, address) values ("Bądźcie dla siebie nawzajem dobrzy i miłosierni! Przebaczajcie sobie, tak jak i Bóg nam przebaczył w Chrystusie.",  "Ef 4,32");
insert into t_bible_verse (text, address) values ("Bądźcie więc naśladowcami Boga, jako dzieci umiłowane, i postępujcie drogą miłości, bo i Chrystus was umiłował i samego siebie wydał za nas w ofierze i dani na wdzięczną wonność Bogu.",  "Ef 5,1-2");
insert into t_bible_verse (text, address) values ("Ku wolności wyswobodził nas Chrystus. A zatem trwajcie w niej i nie poddawajcie się na nowo pod jarzmo niewoli!",  "Ga 5,1");
insert into t_bible_verse (text, address) values ("Bo całe Prawo wypełnia się w tym jednym nakazie: Będziesz miłował bliźniego swego jak siebie samego.",  "Ga 5,14");
insert into t_bible_verse (text, address) values ("Jeśliście więc razem z Chrystusem powstali z martwych, szukajcie tego, co w górze, gdzie przebywa Chrystus zasiadając po prawicy Boga. Dążcie do tego, co w górze, nie do tego, co na ziemi.",  "Kol 3,1-2");
insert into t_bible_verse (text, address) values ("Jako więc wybrańcy Boży - święci i umiłowani - obleczcie się w serdeczne miłosierdzie, dobroć, pokorę, cichość, cierpliwość, znosząc jedni drugich i wybaczając sobie nawzajem, jeśliby miał ktoś zarzut przeciw drugiemu: jak Pan wybaczył wam, tak i wy!",  "Kol 3,12-13");
insert into t_bible_verse (text, address) values ("Trwajcie gorliwie na modlitwie, czuwając na niej wśród dziękczynienia.",  "Kol 4,2");
insert into t_bible_verse (text, address) values ("Weź udział w trudach i przeciwnościach jako dobry żołnierz Chrystusa Jezusa!",  "2 Tm 2,3");
insert into t_bible_verse (text, address) values ("Nauka to zasługująca na wiarę: Jeżeliśmy bowiem z Nim współumarli, wespół z Nim i żyć będziemy. Jeśli trwamy w cierpliwości, wespół z Nim też królować będziemy. Jeśli się będziemy Go zapierali, to i On nas się zaprze.",  "2 Tm,11-12");
insert into t_bible_verse (text, address) values ("Kto doznaje pokusy, niech nie mówi, że Bóg go kusi. Bóg bowiem ani nie podlega pokusie ku złemu, ani też nikogo nie kusi.",  "Jk 1,13");
insert into t_bible_verse (text, address) values ("Każde dobro, jakie otrzymujemy, i wszelki dar doskonały zstępują z góry, od Ojca świateł, u którego nie ma przemiany ani cienia zmienności.",  "Jk 1,17");
insert into t_bible_verse (text, address) values ("Wiedzcie, bracia moi umiłowani: każdy człowiek winien być chętny do słuchania, nieskory do mówienia, nieskory do gniewu. Gniew bowiem męża nie wykonuje sprawiedliwości Bożej.",  "Jk 1,19-20");
insert into t_bible_verse (text, address) values ("Wprowadzajcie zaś słowo w czyn, a nie bądźcie tylko słuchaczami oszukującymi samych siebie. Jeżeli bowiem ktoś przysłuchuje się tylko słowu, a nie wypełnia go, podobny jest do człowieka oglądającego w lustrze swe naturalne odbicie.",  "Jk 1,22-23");
insert into t_bible_verse (text, address) values ("Jaki z tego pożytek, bracia moi, skoro ktoś będzie utrzymywał, że wierzy, a nie będzie spełniał uczynków? Czy [sama] wiara zdoła go zbawić?",  "Jk 2,14");
insert into t_bible_verse (text, address) values ("Tak też i wiara, jeśli nie byłaby połączona z uczynkami, martwa jest sama w sobie.",  "Jk 2,17");
insert into t_bible_verse (text, address) values ("Modlicie się, a nie otrzymujecie, bo się źle modlicie, starając się jedynie o zaspokojenie swych żądz.",  "Jk 4,3");
insert into t_bible_verse (text, address) values ("Jeden jest Prawodawca i Sędzia, w którego mocy jest zbawić lub potępić. A ty kimże jesteś, byś sądził bliźniego?",  "Jk 4,12");
insert into t_bible_verse (text, address) values ("Nie oddawajcie złem za zło ani złorzeczeniem za złorzeczenie! Przeciwnie zaś, błogosławcie!",  "1 P 3,9a");
insert into t_bible_verse (text, address) values ("Przede wszystkim miejcie wytrwałą miłość jedni ku drugim, bo miłość zakrywa wiele grzechów.",  "1 P 4,8");
insert into t_bible_verse (text, address) values ("Ale cieszcie się, im bardziej jesteście uczestnikami cierpień Chrystusowych, abyście się cieszyli i radowali przy objawieniu się Jego chwały.",  "1 P 4,13");
insert into t_bible_verse (text, address) values ("Zatem również ci, którzy cierpią zgodnie z wolą Bożą, niech dobrze czyniąc, wiernemu Stwórcy oddają swe dusze!",  "1 P 4,18");

